# Generated by Django 5.1.2 on 2025-11-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_remove_post_caption_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
