# Generated by Django 5.1.2 on 2025-11-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_alter_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='allow_comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='allow_sharing',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag_people',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
