"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.2.
"""

from pathlib import Path
import os

# ✅ Base Directory
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ Security
SECRET_KEY = 'django-insecure-9vc2j$89+fni-8h2y!=px61uo4+@3#*w3y4vo5tdj(vzre3&+z'
DEBUG = True  # Keep True only for local testing
ALLOWED_HOSTS = ['simpledjango-app-43xf.onrender.com', '127.0.0.1', 'localhost','django-3-v9mp.onrender.com']

CSRF_TRUSTED_ORIGINS = [
    'https://simpledjango-app-43xf.onrender.com',
    'https://django-3-v9mp.onrender.com',
]


# ✅ Installed Apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'basic',
    'app',        # ✅ make sure folder name is 'app'
    'insta',
]

# ✅ Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ✅ URL Config
ROOT_URLCONF = 'myproject.urls'

# ✅ Templates Config (fixed name)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates folder
        'APP_DIRS': True,                  # Look inside app/templates too
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ✅ WSGI Application
WSGI_APPLICATION = 'myproject.wsgi.application'

# ✅ Database (SQLite for simplicity)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}

# ✅ Password Validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ✅ Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ✅ Static Files
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ✅ Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# ✅ Default Primary Key Field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ✅ Login / Logout Redirects (optional)
LOGIN_REDIRECT_URL = '/insta/feed/'
LOGOUT_REDIRECT_URL = '/insta/feed/'
