# Generated by Django 5.1.2 on 2025-11-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_type', models.CharField(max_length=50)),
                ('post_descrioption', models.CharField(max_length=1000)),
            ],
        ),
    ]
