# Generated by Django 5.1.2 on 2025-11-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Rating',
            field=models.CharField(max_length=10),
        ),
    ]
