# Generated by Django 5.1.2 on 2025-12-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreadiCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('ccnum', models.CharField(max_length=20)),
                ('limit', models.IntegerField()),
                ('outstanding', models.IntegerField(default=0)),
            ],
        ),
    ]
