# Generated by Django 5.1.2 on 2025-11-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_postdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='post_descrioption',
            new_name='post_description',
        ),
        migrations.AddField(
            model_name='postdata',
            name='post_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
