# Generated by Django 5.1.2 on 2025-12-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_creadicard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creadicard',
            name='ccnum',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='creadicard',
            name='limit',
            field=models.FloatField(),
        ),
    ]
